
title: 射矢 et 愛華
# email: your-email@example.com
description: >-
  my site
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

lang: ja
timezone: Asia/Tokyo
encoding: utf-8
markdown: kramdown

# Build settings
# theme: minima
#plugins:
#  - jekyll-feed

sass:
  style: compressed
  sass_dir: _sass

collections:
  assets:
    output: true
  pages:
    output: true

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: "/posts/:year/:month/:day/:title/"
  -
    scope:
      path: "_pages"
      # type: "pages"
    values:
      layout: "page"
      permalink: "/:title/" #:output_ext"

